### ISSUE TITLE
Crash on joining, 1.0.2 Involved Harmony IDs: itemrarity.patches

### ISSUE THREAD

**Issue by Xelonie** [raevendev/ItemRarity#1]
Involved Harmony IDs: itemrarity.patches
System.MissingMethodException: Method not found: 'System.String Vintagestory.API.Config.Lang.GetWithFallback(System.String, System.String, System.Object[])'.
   at ItemRarity.Patches.CollectibleObjectPatch.PatchGetHeldItemName(CollectibleObject __instance, ItemStack itemStack, String& __result)
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemName_Patch1(CollectibleObject this, ItemStack itemStack)
   at Vintagestory.API.Common.ItemStack.GetName() in VintagestoryApi\Common\Collectible\ItemStack.cs:line 387
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world) in VintagestoryLib\Common\GameContent\Inventory\CreativeTab.cs:line 40
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world) in VintagestoryLib\Common\GameContent\Inventory\CreativeTabs.cs:line 48
   at Vintagestory.Client.NoObf.GuiDialogInventory.<OnOwnPlayerDataReceived>b__6_0() in VintagestoryLib\Client\Systems\Gui\Dialogs\GuiDialogInventory.cs:line 58
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass13_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 121
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by Unreal852** [comment]
Which version of the game are you using? It seems that your version does not include the GetWithFallback method, which was introduced in Vintage Story v1.20-rc.6.

**Comment by Xelonie** [comment]
v1.20-rc.5, 
i guess i will have to stick with version 1.0.1 for a bit longer, which does work well, besides being unable to break certains blocks
need to wait for other mods to update since rc.6 broke many of em, 
love the mod!
